### ISSUE TITLE
iphone向けビルドができることを確認する

### ISSUE THREAD

**Issue by daigo0907** [enpitut2019/CleanReminder#40]
ネイティブアプリにする予定だが、まだタッチ機能には対応していません。
そこで、まず、iOSでビルドができるかどうかを確認しておきます

**Comment by kugimasa** [comment]
* 恐らくShaderの問題です...
* Unity 2019.2.8f1を入れ直します

**Comment by daigo0907** [comment]
高橋君に入れなおしてもらいましたが、症状は全く変わらずです

**Comment by daigo0907** [comment]
kanbanの中でずっとInProgressにあるのが気持ち悪いので、一時的に諦めます
（別のMacでなら可能かもしれない）
