### ISSUE TITLE
iOSのビルドにチャレンジする

### ISSUE THREAD

**Issue by daigo0907** [enpitut2019/CleanReminder#85]
メンターさんの力を借りてチャレンジします

**Comment by daigo0907** [comment]
釘メンターのMacでビルドしてみたが、結論的には無理でした

主な原因はシェーダーコンパイラの部分にあるようで、、
MacOSの最新版が、Unity2.8や2.9でのビルドを邪魔をしている
詳細は以下を参照
https://forum.unity.com/threads/unknown-shader-compiler-error-using-unity-2019-2-8f1-when-building-ios.758339/
解決策は以下を参照
https://qiita.com/JunNishimura/items/c94453498fe69f1d71ff

**Comment by daigo0907** [comment]
原因が分かったが、時間の都合で今回は無理だった
次回またお願いすることになりました。

**Comment by kugimasa** [comment]
全力でサポートしますのでもうしばらくお待ちください....!!

**Comment by kugimasa** [comment]
現在Unityのバージョン2019.3.0b11でのビルドを試みています。
ビルドの際に以下のエラーが出ているのでその対処にあたっています。
![スクリーンショット 2019-11-25 16 41 29](https://user-images.githubusercontent.com/40158101/69521486-775e2a80-0fa2-11ea-9995-df0f79cec9cd.png)

**Comment by kugimasa** [comment]
Unity Version 2019.2.10f1でのiOSビルド確認できました
以下のリンクの方法にしたがってUnity Shader Compiler をUnity Version 2019.3.0.b11のものに入れ替えてください
Libraryの削除についてはリポジトリのcloneからする場合は必要ないです(GitHubのリモートにはLibraryが存在しないので)
https://qiita.com/JunNishimura/items/c94453498fe69f1d71ff
